language: go

go:
  - 1.15.5

install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.34.1
  - go get -t ./...

script:
  - golangci-lint run --skip-dirs v1
  - go test ./... -timeout 120s
